markdown: kramdown
permalink: /:categories/blog/:year/:month/:day/:title.html
paginate: 5
url: http://groonga.org

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
  coderay_line_numbers: nil
