markdown: kramdown
permalink: /:categories/blog/:year/:month/:day/:title.html
paginate: 5
url: http://groonga.org
future: true
incremental: true
groonga_version: 6.1.1
groonga_release_date: 2016-11-29

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
  coderay_line_numbers: nil
gems: [jekyll-paginate]

defaults:
  - scope:
      path: "ja/blog"
    values:
      layout: "ja"
      language: ja
      country: JP
      title: BloGroonga
      heading_link: /ja/blog/
      relative_url: blog/
  - scope:
      path: "ja"
      type: "posts"
    values:
      layout: "post.ja"
      language: ja
      country: JP
      heading: BloGroonga
      heading_link: /ja/blog/
      relative_url: blog/
  - scope:
      path: "blog"
    values:
      layout: "en"
      language: en
      country: US
      title: BloGroonga
      heading_link: /blog/
      relative_url: blog/
  - scope:
      path: "en"
      type: "posts"
    values:
      layout: "post.en"
      language: en
      country: US
      heading: BloGroonga
      heading_link: /blog/
      relative_url: blog/
  - scope:
      path: "ja"
    values:
      layout: "ja"
      language: ja
      country: JP
  - scope:
      path: ""
    values:
      layout: "en"
      language: en
      country: US
